[workspace.package]
name = "tcp_client_server_echo_app"
rust-version = "1.76"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["badroboyenergy@gmail.com", "Bluealternate2"]
version = "0,0.5"
